import {configureStore, createSlice} from '@reduxjs/toolkit'

const authSlice = createSlice({
name: "auth",
initialState: {isLoggedIn : false},
reducers :{
    login(state){
state.isLoggedIn = true;
    },
    logout(state){
        localStorage.removeItem('userId');
        state.isLoggedIn = false;
    },
},
});

export const authActions = authSlice.actions;

export const store = configureStore({
    reducer: authSlice.reducer,
})

//store is the central data for (state), the store is subcribed to the components
//reducer Function - mutates the store data 
//components dispatch actions that is then fowarded to the reducer function

//This code is using the createSlice and configureStore functions from the @reduxjs/toolkit package to create a Redux store with a slice of state for handling authentication.
//The createSlice function is used to create a "slice" of the Redux store's state. It takes an object with the following properties:
//name: A string that identifies the slice.
//initialState: The initial state of the slice.
//reducers: An object that defines the actions that can be dispatched to update the slice's state.
//In this code, the createSlice function is called with an object that defines a slice of state for handling authentication. The initial state of the slice is an object with a single property isLoggedIn set to false. The reducers object defines two actions, login and logout, which update the isLoggedIn property of the state to true and false, respectively.
//The authActions object is created by calling the actions property of the authSlice. This object contains the login and logout action creators that can be dispatched to update the state of the authSlice.
//The configureStore function is used to create the Redux store. It takes an object with the following properties:
//reducer: The root reducer function that combines all the slices of state into a single state tree.
//In this code, the configureStore function is called with an object that sets the reducer property to the reducer function generated by the createSlice function. This creates a Redux store with a single slice of state for handling authentication.
//Overall, this code is creating a Redux store with a slice of state for handling authentication, including two actions login and logout to update the state of the isLoggedIn property, and exporting the authActions object and the Redux store.